#define N_NUM_BITS 1024
#define RSA_NUM_BITS 512
#define E_NUM_BITS 24
#define DEBUG 0
#define PUB_KEY_BUF_LEN 10000
#define TAG_LEN 5
#define CLASS_LEN 2
#define TAG_INT 2
#define PRIMITIVE 0
#define CONSTRUCTED 1
#define UNIVERSAL 0
#define TAG_SEQUENCE 16
#define TAG_BIT_STRING 3
#define TAG_NULL 5
#define TAG_OID 6
#define PRIV_KEY_BUF_LEN 10240
#define MSG_BUF_LEN 1024
